language: python
sudo: false
python:
  - "2.7"
install:
  - pip install -r requirements.txt
  - pip install isort
  - pip install flake8
  - pip install -e .
  - pip list
script:
  - make check-isort
  - make check-flake8
  - python setup.py test
